### PR TITLE
Review of OCF content format version options

### PR DESCRIPTION
**Pull request by ektrah**

### CODE REVIEW

**Comment by mjkoster** [comment]
I need a little more explanation of the following; which are required and what is expected:

Scarcity of Code Points
Protocol Extension
Conflict
Clients and Origin Servers
Caches and Intermediaries

**Comment by ektrah** [comment]
@mjkoster - Those are the items for the expert to evaluate (see [RFC 5226 Section 3.3](https://tools.ietf.org/html/rfc5226#section-3.3) for details if you're interested). From you we need the specification of the option, i.e., the items listed in [RFC 7252 Section 12.2](https://tools.ietf.org/html/rfc7252#section-12.2) (critical, critical, safe-to-forward, format, length, etc.).

**Comment by mjkoster** [comment]
OK, Thanks. I think I have it ready to go then.

**Comment by mjkoster** [comment]
I see you did some more updates. Why is the accept version not a critical option? I requested 2049 as a critical option because the server needs to know which serializer to use.

**Comment by ektrah** [comment]
@mjkoster - 2048 is what I gathered from the discussion; I don't have the original registration request. This is the reason we're doing the review - to catch little mistakes like off-by-one errors. I've updated the number in the review report to 2049.

**Comment by ektrah** [comment]
@mjkoster - For comparison:

| Number | Name | Critical | NotSafeToForward | NotPartOfCacheKey |
| -:| - | - | - | - |
| 12 | Content-Format | ***false*** | false | false |
| 2053 | OCF-Content-Format-Version | ***true*** | false | false |
| 17 | Accept | true | false | false |
| 2049 | OCF-Accept-Content-Format-Version | true | false | false |

* Why is OCF-Content-Format-Version critical and not elective like Content-Format?
* Do you want to shorten OCF-Accept-Content-Format-Version to OCF-Accept-Version?
* Can OCF-Content-Format-Version be used both in requests and responses or only in responses?

**Pull request merged**
